server:
  port: 8181
    #8181
spring:
  application:
    name: vehicle-reservation
  datasource:
    url: jdbc:postgresql://vehicle-reservation-db.cjcu4csk4f7b.us-east-2.rds.amazonaws.com/vehicle_reservation
    #jdbc:postgresql://localhost:5432/vehicle_reservation_system
    username: postgres
    password: Admin*2024#
    driver-class-name: org.postgresql.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      #      ddl-auto: create
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
application:
  security:
    jwt:
      secret-key: d5608c2a97c84dd0c0e0374ab865a131e0305df3f642ff83a03d796d748ac251
      expiration: 86400000 # a day

